### ISSUE TITLE
Render issue on a server connection.

### ISSUE THREAD

**Issue by Warlozy** [CreativeMD/OnlinePictureFrame#3] opened 2017-03-08 20:16 UTC
[crash-2017-03-08_15.10.08-client.txt](https://github.com/CreativeMD/OnlinePictureFrame/files/828840/crash-2017-03-08_15.10.08-client.txt)

Upon selecting a link to a google drive photo the screen attempted to load the photo. This caused the client side display to completely become white/black.

I think its that the photo couldn't be loaded causing the rendering issue.

**Comment by CreativeMD** [comment] 2017-03-08 20:25
Could you send me the link of the photo? So i can do some testing?

**Comment by Warlozy** [comment] 2017-03-08 20:26
https://drive.google.com/open?id=0B3YejVL4u6DUblgxMGhydkU3d0E

**Comment by Warlozy** [comment] 2017-03-08 20:27
Was just testing the mod initially to see about adding some decorations around where we've set up base.

**Comment by CreativeMD** [comment] 2017-03-08 21:01
The problem is that your link is not an image, but a website showing an image. I don't know if it's possible using google drive to get the direct link to the image, I rather recommend to use imgur instead.

Nonetheless the game shouldn't crash while trying to load an invalid url and this is fixed in v1.3.3 (which will be available soon).
Thanks for reporting.

**Closed as completed by CreativeMD** 2017-03-08 21:01 UTC

**Comment by Warlozy** [comment] 2017-03-08 21:02
No problem, have a nice day.
